# Create a self-signed certificate
# The certificate is stored in a Secret named selfsigned-cert-tls
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
spec:
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
    kind: ClusterIssuer
  dnsNames:
    - nginx-cluster.local
